server:
  port: 9000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/tienda-online

  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:9001

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info