spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce
    username: ${VAULT_DB_USERNAME}
    password: ${VAULT_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 60000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: tienda-online


  cloud:
    vault:
      token: myroot
      scheme: http
      host: vault
      port: 8200

      database:
        enabled: true
        role: myrole
        backend: database