spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce
    username: ${vault:secret/postgres_db/db_username}
    password: ${vault:secret/postgres_db/db_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: tienda-online